version: '3'
services:
  uwsgi:
    build: ./app
    volumes:
      - ./app:/var/www/
    ports:
      - 3031:3031

  nginx:
    build: ./nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - 80:80
      - 443:443
